dist: xenial
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
before_install:
  - travis_retry npm install -g lerna
install:
  - |
    if [[ $TRAVIS_BRANCH == *"greenkeeper"* ]]; then
      travis_retry npm run lerna:bootstrap:no-ci;
    else
      travis_retry npm run lerna:bootstrap:ci;
    fi
before_script:
  - |
    if [[ $TRAVIS_BRANCH == *"greenkeeper"* ]]; then
      npm run greenkeeper:lockfile:update;
    fi
script:
  - npm run clean
  - npm run lint
  - npm run copy:static
  - npm run build:prod
  #- INSTALL_CMD="echo 'happo-ci-travis'" npm run happo-ci-travis
after_script:
  - |
    if [[ $TRAVIS_BRANCH == *"greenkeeper"* ]]; then
      npm run greenkeeper:lockfile:upload;
    fi
branches:
  only:
    - master
    - /^greenkeeper.*$/
